server:
  port: 8002
spring:
  application:
    name: dept-service
  cloud:
    nacos:
      discovery:
        namespace: 46cb442f-d169-47c4-a8b1-2bf0ac9e4832
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        namespace: 46cb442f-d169-47c4-a8b1-2bf0ac9e4832
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

feign:
  okhttp:
    enable: true